apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: statistical-krill-go 
  janus-idp.io/tekton: statistical-krill-go
  backstage.io/kubernetes-id: statistical-krill-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: statistical-krill-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  