apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: statistical-krill-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statistical-krill-go 
  name: statistical-krill-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: statistical-krill-go 
